import type { CasoId, CasoPublico } from "./tipos";

export const CASOS_PUBLICOS: Record<CasoId, CasoPublico> = {
  davi: {
    id: "davi",
    titulo: "Davi, 1 ano e 8 meses",
    contexto: "Visita domiciliar. Marcos, pai do Davi (1 ano e 8 meses), atende a porta.",
    quem: "Marcos, 29 anos, pai do Davi, um menino de 1 ano e 8 meses",
    persona: "Você está muito preocupado e um pouco agitado, fala meio rápido. É seu primeiro filho e você nunca viu ele assim. Você pergunta o que fazer e repete que a febre não passa de jeito nenhum. Você fala sobre o Davi, não sobre você.",
    queixa: "o Davi está com febre há 3 dias, chegou a 39 graus, e está chorando mais que o normal",
    saudacao: "Oi, bom dia! Ainda bem que você veio. É o Davi, tá com febre desde domingo e não passa de jeito nenhum.",
    perguntaDoPaciente: "Posso dar aquela aspirina infantil pra baixar a febre dele?",
    revisadoPor: null,
    revisadoEm: null,
  },
  joaquim: {
    id: "joaquim",
    titulo: "Seu Joaquim, 70 anos",
    contexto: "Visita domiciliar. Seu Joaquim, 70 anos, hipertenso, está na varanda.",
    quem: "Joaquim, 70 anos, aposentado",
    persona: "Você é simpático e minimiza tudo, sempre diz que não é nada.",
    queixa: "teve febre alta nos últimos dias, mas acha que já está melhorando",
    saudacao: "Bom dia, meu filho! Pode sentar. Tive uma febre braba aí, mas acho que já tô melhor.",
    perguntaDoPaciente: "Preciso ir mesmo? Já tô melhor, a febre passou.",
    revisadoPor: null,
    revisadoEm: null,
  },
  rafa: {
    id: "rafa",
    titulo: "Rafa, 22 anos",
    contexto: "Visita domiciliar. Rafa, 22 anos, abre a porta de moletom.",
    quem: "Rafa, 22 anos, estudante",
    persona: "Você é meio desleixado com a saúde e acha que tudo vai passar sozinho.",
    queixa: "está com febre há 4 dias e o corpo todo doendo",
    saudacao: "E aí, tudo bem? Pode entrar. Tô meio largado, febre faz uns quatro dias.",
    perguntaDoPaciente: "Posso tomar mais daquele anti-inflamatório? Ajudou na dor.",
    revisadoPor: null,
    revisadoEm: null,
  },
  juliana: {
    id: "juliana",
    titulo: "Juliana",
    contexto: "Visita domiciliar. Pedro, marido da Juliana, atende a porta.",
    quem: "Pedro, 31 anos, marido da Juliana",
    persona: "Você está tranquilo, acha que é só gripe. Você fala sobre a Juliana, não sobre você.",
    queixa: "a Juliana está com febre há dois dias e dor no corpo, está deitada lá dentro",
    saudacao: "Oi, boa tarde! É a Juliana, minha esposa, tá de cama com febre desde ontem de manhã.",
    perguntaDoPaciente: "Ela pode tomar aquele remédio de gripe que tem aqui?",
    revisadoPor: null,
    revisadoEm: null,
  },
  celia: {
    id: "celia",
    titulo: "Dona Célia, 64 anos",
    contexto: "Visita domiciliar. Roberto, filho de Dona Célia, atende a porta.",
    quem: "Roberto, 38 anos, filho de Dona Célia",
    persona: "Você está preocupado mas prático. Você fala sobre a mãe, não sobre você.",
    queixa: "a mãe está com febre há três dias, dor nas juntas e muito cansada",
    saudacao: "Bom dia! Entra, por favor. É a minha mãe, Dona Célia, tá com febre faz uns três dias.",
    perguntaDoPaciente: "Precisa mesmo levar ela no posto? Ela detesta ir lá.",
    revisadoPor: null,
    revisadoEm: null,
  },
};
